name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build-deps
      run: sudo apt-get -y install libfuse-dev
    - name: make
      run: make

    - name: copy-binary
      uses: actions/upload-artifact@v4
      with:
        name: adbfs-bin
        retention-days: 5
        path: |
          ./adbfs
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emulator:
          - { 'api_level': 35, 'api_type_target': 'google_apis', 'arch': 'x86_64' }
          - { 'api_level': 34, 'api_type_target': 'default', 'arch': 'x86_64' }
          - { 'api_level': 33, 'api_type_target': 'aosp_atd', 'arch': 'x86_64' }
          - { 'api_level': 32, 'api_type_target': 'aosp_atd', 'arch': 'x86_64' }
          - { 'api_level': 31, 'api_type_target': 'aosp_atd', 'arch': 'x86_64' }
          - { 'api_level': 30, 'api_type_target': 'aosp_atd', 'arch': 'x86_64' }
          - { 'api_level': 30, 'api_type_target': 'aosp_atd', 'arch': 'x86' }
          - { 'api_level': 29, 'api_type_target': 'default', 'arch': 'x86_64' }
          - { 'api_level': 29, 'api_type_target': 'default', 'arch': 'x86' }
          - { 'api_level': 28, 'api_type_target': 'default', 'arch': 'x86_64' }
          - { 'api_level': 28, 'api_type_target': 'default', 'arch': 'x86' }
          - { 'api_level': 27, 'api_type_target': 'default', 'arch': 'x86_64' }
          - { 'api_level': 27, 'api_type_target': 'default', 'arch': 'x86' }
          - { 'api_level': 26, 'api_type_target': 'default', 'arch': 'x86_64' }
          - { 'api_level': 26, 'api_type_target': 'default', 'arch': 'x86' }
          - { 'api_level': 25, 'api_type_target': 'default', 'arch': 'x86_64' }
          - { 'api_level': 25, 'api_type_target': 'default', 'arch': 'x86' }
          - { 'api_level': 24, 'api_type_target': 'default', 'arch': 'x86_64' }
          - { 'api_level': 24, 'api_type_target': 'default', 'arch': 'x86' }
          - { 'api_level': 23, 'api_type_target': 'default', 'arch': 'x86_64' }
          - { 'api_level': 23, 'api_type_target': 'default', 'arch': 'x86' }
          - { 'api_level': 22, 'api_type_target': 'default', 'arch': 'x86_64' }
          - { 'api_level': 22, 'api_type_target': 'default', 'arch': 'x86' }
          - { 'api_level': 21, 'api_type_target': 'default', 'arch': 'x86_64' }
          - { 'api_level': 21, 'api_type_target': 'default', 'arch': 'x86' }

          - { 'api_level': 19, 'api_type_target': 'default', 'arch': 'x86' }
          - { 'api_level': 18, 'api_type_target': 'default', 'arch': 'x86' }
          - { 'api_level': 17, 'api_type_target': 'default', 'arch': 'x86' }
          - { 'api_level': 16, 'api_type_target': 'default', 'arch': 'x86' }
          - { 'api_level': 15, 'api_type_target': 'default', 'arch': 'x86' }
    steps:
    - uses: actions/checkout@v4
    - name: prepare
      run: sudo apt-get update && sudo apt-get install -y fuse libfuse-dev

    - name: make
      run: make

    - name: copy adbfs binary
      run: |
        sudo cp ${{ github.workspace }}/adbfs /usr/bin/adbfs
        sudo chmod +x /usr/bin/adbfs
    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.emulator.api_level }}
        arch: ${{ matrix.emulator.arch }}
        target: ${{ matrix.emulator.api_type_target }}
        script: sudo ./docker/run-docker-test.sh
    # services:
      # emulator:
        # image: budtmo/docker-android:emulator_12.0
        # options: --privileged
      # - name: run-tests
      #   run: sudo bash ./docker/run-docker-test.sh